### PR TITLE
add nahuatl morphological analysis

### PR DESCRIPTION
**Pull request by ftyers**
Here is a pull request to add Western Sierra Puebla Nahuatl morphological analysis to pyelotl. The analyser used is the Pugh et al. one, and the code does conversion from that tagset to Universal Dependencies. 

There are a lot of decisions to be made regarding how best the data and code should be organised in the repository. I would propose having the morphological analysis code separate (maybe in `utils/`) and then have the language data in the individual language directories. There are also analysers for San Mateo Huave [`huv`](https://github.com/apertium/apertium-huv) and Colonial Valley Zapotec [`zab`](https://github.com/apertium/apertium-zab) that it would be nice to include, but I will send them as separate PRs. 

Here is an example script:

```python
from elotl.nahuatl.morphology import Analyser
a = Analyser()
res = a.analyse('Huan nomama onechilhuaya, “Amo quen ximati, teh xiyo in escuela.', tokenise=True)
for token in res:
	for analysis in token.analyses:
		print(token, analysis)
```

and an example of the output:

```bash
fran@ipek:~/source/py-elotl$ python3 foo.py 
<Token "Huan" (1)> ([{'lemma': 'huan', 'pos': 'CCONJ', 'feats': set()}], 0.0)
<Token "nomama" (2)> ([{'lemma': 'mama', 'pos': 'NOUN', 'feats': {'Person[psor]=1', 'Number[psor]=Sing'}}], 0.0)
<Token "nomama" (2)> ([{'lemma': 'mama', 'pos': 'NOUN', 'feats': {'Number[subj]=Sing', 'Person[subj]=3', 'Person[psor]=1', 'Number[psor]=Sing'}}], 0.0)
<Token "onechilhuaya" (1)> ([{'lemma': 'ilhuia', 'pos': 'VERB', 'feats': {'VerbForm=Fin', 'Aspect=Impf', 'Number[subj]=Sing', 'Tense=Past', 'Person[subj]=3'}}], 0.0)
<Token "," (1)> ([{'lemma': ',', 'pos': 'PUNCT', 'feats': set()}], 0.0)
<Token "“" (1)> ([{'lemma': '“', 'pos': '', 'feats': set()}], 0.0)
<Token "Amo" (1)> ([{'lemma': 'amo', 'pos': '', 'feats': set()}], 0.0)
<Token "quen" (1)> ([{'lemma': 'quen', 'pos': 'ADV', 'feats': set()}], 0.0)
<Token "ximati" (2)> ([{'lemma': 'mati', 'pos': 'VERB', 'feats': {'Number[subj]=Sing', 'Subcat=Tran', 'Mood=Opt', 'Person[subj]=2'}}], 0.0)
<Token "ximati" (2)> ([{'lemma': 'mati', 'pos': 'VERB', 'feats': {'Person[subj]=2', 'Person[obj]=3', 'Number[subj]=Sing', 'Subcat=Tran', 'Mood=Opt', 'Number[obj]=Sing'}}], 0.0)
<Token "," (1)> ([{'lemma': ',', 'pos': 'PUNCT', 'feats': set()}], 0.0)
<Token "teh" (1)> ([{'lemma': 'tehuatl', 'pos': 'PRON', 'feats': {'PronType=Prs', 'Person=2', 'Number=Sing'}}], 0.0)
<Token "in" (1)> ([{'lemma': 'in', 'pos': 'DET', 'feats': set()}], 0.0)
<Token "escuela" (2)> ([{'lemma': 'escuela', 'pos': 'NOUN', 'feats': set()}], 0.0)
<Token "escuela" (2)> ([{'lemma': 'escuela', 'pos': 'NOUN', 'feats': {'Number[subj]=Sing', 'Person[subj]=3'}}], 0.0)
<Token "." (1)> ([{'lemma': '.', 'pos': 'PUNCT', 'feats': set()}], 0.0)
```

Comments and suggestions very welcome!

### CODE REVIEW

**Comment by Lguyogiro** [comment]
This is great thanks! I ran a few examples locally and it worked well.

A few minor things, maybe they don't need to be addressed immediately, i.e. they can be added in future PRs (but it is important to highlight them here so that they aren't forgotten):
* documentation: We don't have like a contributor's guide, but we should have specifically-formatted docstrings for most/all functions. The existing code (at least for the orthographic normalizers) use numpy docstrings, so let's either stick with that or decide on something else and change the existing docstrings.
* tests: probably worth adding a few unit tests so that we can track any regressions and general library functionality
* spelling: words like analyse/analyze  we should maybe just add an alias so that either works. This also goes for the existing "Normalizer" api :sweat_smile: 

Overall, though, LGTM! I'm happy that to see activity on this project again after a bit of a lull!

**Comment by Lguyogiro** [comment]
Oh and I like this suggestion:

> I would propose having the morphological analysis code separate (maybe in utils/) and then have the language data in the individual language directories

**Comment by ftyers** [comment]
Thanks for the feedback! 

- I've taken care of the spelling, so that now both `analyze` and `analyse` work. 
- I've started work on the docstrings, I'll finish those before asking you to merge.
- About the testing setup, do you have any suggestions? Are there any other tests set up?

Also, for the separation of code/data I think that maybe for this PR let's keep it as is, and then in the next PR I can factor out the analysis code when I add Huave.

**Comment by ftyers** [comment]
Otra idea que tuve es que podríamos tener en lugar de un conjunto para los pares de característica--valor un diccionario donde cada llave es la característica, tipo:
```python
<Token form="monamacaz" lemma="namaca" pos="VERB" analyses="1">
	 ([{'lemma': 'namaca', 'pos': 'VERB', 'feats': {'Tense': 'Fut', 'Number[subj]': 'Sing',
                      'Person[subj]': '3', 'Reflexive': 'Yes', 'Subcat': 'Tran', 'VerbForm': 'Fin'}}], 0.0)
```
Podría ser más conveniente tractar así. ¿Qué opináis?

**Comment by Lguyogiro** [comment]
De acuerdo, creo que seria mas conveniente si los Features fuera un diccionario con `{<feat>: <val>}`

**Comment by Lguyogiro** [comment]
> Thanks for the feedback!
> 
>     * [x]   I've taken care of the spelling, so that now both `analyze` and `analyse` work.
> 
>     * [x]  I've started work on the docstrings, I'll finish those before asking you to merge.
> 
>     * [ ]  About the testing setup, do you have any suggestions? Are there any other tests set up?
> 
> 
> Also, for the separation of code/data I think that maybe for this PR let's keep it as is, and then in the next PR I can factor out the analysis code when I add Huave.

We used unittest for the orthography stuff. It is really basic and could probably be expanded in the future: [test_nahuatl_orthography.py](https://github.com/ElotlMX/py-elotl/blob/master/tests/test_nahuatl_orthography.py)

**Comment by ftyers** [comment]
Added a couple of simple tests.

**Pull request merged**
